export const tasks = [{
    "Task_ID":1,"Task_Assigned_Employee_ID":7,"Task_Owner_ID":1,"Task_Customer_Employee_ID":null,"Task_Subject":"Prepare 2013 Financial","Task_Description":"<div>IMPORTANT: The document must be fully formatted in Excel.</div>","Task_Start_Date":"2013-01-15T00:00:00","Task_Due_Date":"2013-01-31T00:00:00","Task_Status":"Completed","Task_Priority":4,"Task_Completion":100,"Task_Reminder":true,"Task_Reminder_Date":"2014-01-20T00:00:00","Task_Reminder_Time":"1899-12-30T08:00:00","SSMA_TimeStamp":"AAAAAAAAG1k="
},{
    "Task_ID":2,"Task_Assigned_Employee_ID":4,"Task_Owner_ID":1,"Task_Customer_Employee_ID":null,"Task_Subject":"Prepare 3013 Marketing Plan","Task_Description":"<div>We need to double revenues in 2013 and our marketing strategy is going to be key here. R&amp;D is improving existing products and creating new products so we can deliver great AV equipment to our customers.</div>\r\n\r\n<div>Robert, please make certain to create a PowerPoint presentation for the members of the executive team.</div>","Task_Start_Date":"2013-01-01T00:00:00","Task_Due_Date":"2013-01-31T00:00:00","Task_Status":"Completed","Task_Priority":4,"Task_Completion":100,"Task_Reminder":false,"Task_Reminder_Date":null,"Task_Reminder_Time":null,"SSMA_TimeStamp":"AAAAAAAAG1o="
},{
    "Task_ID":3,"Task_Assigned_Employee_ID":2,"Task_Owner_ID":1,"Task_Customer_Employee_ID":null,"Task_Subject":"Update Personnel Files","Task_Description":"<div>In an audit I conducted of personnel files this, I found documentation to be lacking. Samantha, you need to review my report and get this fixed.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: John, I've completed this review and sent my report to you.</div>","Task_Start_Date":"2013-02-03T00:00:00","Task_Due_Date":"2013-02-28T00:00:00","Task_Status":"Completed","Task_Priority":4,"Task_Completion":100,"Task_Reminder":true,"Task_Reminder_Date":"2013-02-27T00:00:00","Task_Reminder_Time":"1899-12-30T09:00:00","SSMA_TimeStamp":"AAAAAAAAG1s="
},{
    "Task_ID":4,"Task_Assigned_Employee_ID":2,"Task_Owner_ID":1,"Task_Customer_Employee_ID":null,"Task_Subject":"Review Health Insurance Options Under the Affordable Care Act","Task_Description":"<div>The changes in health insurance laws require that we review our existing coverage and update it to meet regulations. &nbsp;Samantha Bright will be point on this.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Samantha Bright: Update - still working with the insurance company to update our coverages.</div>","Task_Start_Date":"2013-02-12T00:00:00","Task_Due_Date":"2013-04-25T00:00:00","Task_Status":"In Progress","Task_Priority":4,"Task_Completion":50,"Task_Reminder":true,"Task_Reminder_Date":"2014-04-23T00:00:00","Task_Reminder_Time":"1899-12-30T09:00:00","SSMA_TimeStamp":"AAAAAAAAG1w="
},{
    "Task_ID":5,"Task_Assigned_Employee_ID":1,"Task_Owner_ID":2,"Task_Customer_Employee_ID":null,"Task_Subject":"Choose between PPO and HMO Health Plan","Task_Description":"<div>We need a final decision on whether we are planning on staying with a PPO Health Plan or we plan on switching to an HMO. We cannot proceed with compliance with the Affordable Health Act until we make this decision.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: Samantha, I'm still reviewing costs. I am not in a position to make a final decision at this point.</div>","Task_Start_Date":"2013-02-15T00:00:00","Task_Due_Date":"2013-04-15T00:00:00","Task_Status":"In Progress","Task_Priority":4,"Task_Completion":75,"Task_Reminder":false,"Task_Reminder_Date":null,"Task_Reminder_Time":null,"SSMA_TimeStamp":"AAAAAAAAG10="
},{
    "Task_ID":6,"Task_Assigned_Employee_ID":1,"Task_Owner_ID":4,"Task_Customer_Employee_ID":null,"Task_Subject":"Google AdWords Strategy","Task_Description":"<div>Make final decision on whether we are going to increase our Google AdWord spend based on our 2013 marketing plan. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>We must seriously consider a higher spend if we are going to double revenues this year.</div>","Task_Start_Date":"2013-02-16T00:00:00","Task_Due_Date":"2013-02-28T00:00:00","Task_Status":"Completed","Task_Priority":4,"Task_Completion":100,"Task_Reminder":false,"Task_Reminder_Date":null,"Task_Reminder_Time":null,"SSMA_TimeStamp":"AAAAAAAAG14="
},{
    "Task_ID":7,"Task_Assigned_Employee_ID":1,"Task_Owner_ID":4,"Task_Customer_Employee_ID":null,"Task_Subject":"New Brochures","Task_Description":"<div>Review and the new brochure designs and give final approval. &nbsp;</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>John Heart: I've reviewed them all and forwarded an email with all changes we need to make to the brochures to comply with local regulations.</div>","Task_Start_Date":"2013-02-17T00:00:00","Task_Due_Date":"2013-02-24T00:00:00","Task_Status":"Completed","Task_Priority":2,"Task_Completion":100,"Task_Reminder":true,"Task_Reminder_Date":"2013-02-24T00:00:00","Task_Reminder_Time":"1899-12-30T10:00:00","SSMA_TimeStamp":"AAAAAAAAG5I="
},{
    "Task_ID":8,"Task_Assigned_Employee_ID":28,"Task_Owner_ID":1,"Task_Customer_Employee_ID":null,"Task_Subject":"2013 Brochure Designs","Task_Description":"<div>The changes we need to make to our 2013 brochures have been forwarded via Email please review and send updated versions to Robert Reagan.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Morgan Kennedy: This task has been completed. New designs are published on our server.</div>","Task_Start_Date":"2013-02-19T00:00:00","Task_Due_Date":"2013-02-24T00:00:00","Task_Status":"Completed","Task_Priority":3,"Task_Completion":100,"Task_Reminder":false,"Task_Reminder_Date":null,"Task_Reminder_Time":null,"SSMA_TimeStamp":"AAAAAAAAGA8="
},{
    "Task_ID":9,"Task_Assigned_Employee_ID":29,"Task_Owner_ID":28,"Task_Customer_Employee_ID":null,"Task_Subject":"Brochure Design Review","Task_Description":"<div>We have been instructed by management to modify brochure designs for 2013. All specifications and change requests are on the server.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Violet Bailey: What did you want me to do besides create the icons we'll be using in the brochure?</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Morgan Kennedy: That's it. Thanks</div>","Task_Start_Date":"2013-02-19T00:00:00","Task_Due_Date":"2013-02-22T00:00:00","Task_Status":"Completed","Task_Priority":2,"Task_Completion":100,"Task_Reminder":false,"Task_Reminder_Date":null,"Task_Reminder_Time":null,"SSMA_TimeStamp":"AAAAAAAAG5M="
},{
    "Task_ID":10,"Task_Assigned_Employee_ID":29,"Task_Owner_ID":28,"Task_Customer_Employee_ID":null,"Task_Subject":"Website Re-Design Plan","Task_Description":"<div>The changes in our brochure designs for 2013 require us to update key areas of our website. </div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Violet Bailey: I've completed the plan and have submitted it to Robert for his approval.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>&nbsp;</div>","Task_Start_Date":"2013-02-19T00:00:00","Task_Due_Date":"2013-02-24T00:00:00","Task_Status":"Completed","Task_Priority":4,"Task_Completion":100,"Task_Reminder":true,"Task_Reminder_Date":"2013-02-24T00:00:00","Task_Reminder_Time":"1899-12-30T11:00:00","SSMA_TimeStamp":"AAAAAAAAG18="
},{
    "Task_ID":11,"Task_Assigned_Employee_ID":4,"Task_Owner_ID":1,"Task_Customer_Employee_ID":null,"Task_Subject":"Rollout of New Website and Marketing Brochures","Task_Description":"<div>The designs for new brochures and website have been approved. Launch date is set for Feb 28.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Robert Reagan: Designers and IT departments have implemented all requirements. The rollout is complete.</div>","Task_Start_Date":"2013-02-20T00:00:00","Task_Due_Date":"2013-02-28T00:00:00","Task_Status":"Completed","Task_Priority":4,"Task_Completion":100,"Task_Reminder":false,"Task_Reminder_Date":null,"Task_Reminder_Time":null,"SSMA_TimeStamp":"AAAAAAAAG2A="
},{
    "Task_ID":12,"Task_Assigned_Employee_ID":8,"Task_Owner_ID":4,"Task_Customer_Employee_ID":null,"Task_Subject":"Update Sales Strategy Documents","Task_Description":"<div>Changes in marketing strategy require an update to our direct sales strategy. The report has to be completed by month's end to submission to the CEO.</div>\r\n\r\n<div>&nbsp;</div>\r\n\r\n<div>Ed Holmes: As you will see in my report, I do not recommend any major changes. </div>","Task_Start_Date":"2013-02-20T00:00:00","Task_Due_Date":"2013-02-22T00:00:00","Task_Status":"Completed","Task_Priority":2,"Task_Completion":100,"Task_Reminder":true,"Task_Reminder_Date":"2013-02-20T00:00:00","Task_Reminder_Time":"1899-12-30T10:00:00","SSMA_TimeStamp":"AAAAAAAAG5Q="
}];
